### ISSUE TITLE
patches for duallink

### ISSUE THREAD

**Issue by nijhawank** [Goldfish64/ArrandaleGraphicsHackintosh#1]
Hi there, do you know the patches for duallink to handle higher resolution display?
Thanks in advance.

**Comment by Goldfish64** [comment]
There aren't patches required for dual link, as the kext uses dual link by default. You'd have to check other sources to be sure of that though.

**Comment by nijhawank** [comment]
So I will try removing the single link patches but leaving the other (stride, linkwidth, fbccontrol, featurecontrol) patches in place and verify the results

**Comment by nijhawank** [comment]
Worked perfect after removing the single link patches. Thank you very much.
